### PR TITLE
 github release by tag

### PR DESCRIPTION
**Pull request by pavertomato**
[#12]

### CODE REVIEW

**Comment by poojavenkatram** [comment]
Can you please also add some documentation on how to release? Maybe we can add this to our Readme.md?

**Comment by pavertomato** [comment]
may be wiki is good place for release documentation? but for the moment i don't have write access to it

**Comment by poojavenkatram** [comment]
That is an interesting idea - is that where we are adding the release steps for other projects?

**Comment by pavertomato** [comment]
yes, and content will be almost exactly same

**Comment by poojavenkatram** [comment]
Ah ok sounds good

**Comment by poojavenkatram** [comment]
Let me merge this and we can take updating the wiki in a follow up

**Review by poojavenkatram — APPROVED** [review]

**Pull request merged**
