### PR TITLE
Upgrade log4j version to 2.15.0

### PR DESCRIPTION
**Pull request by msbukal**

### CODE REVIEW

**Comment by pavertomato** [comment]
seems like openmicroscopy does not host java artifacts of openslide anymore
you might consider update qupath https://github.com/GoogleCloudPlatform/qupath-chcapi-extension/blob/develop/cloudbuild.yaml#L10 probably this issue already solved

**Comment by msbukal** [comment]
Ignoring presubmit build failure as unrelated, merging PR.

**Comment by pavertomato** [comment]
what is the point of update of dependency inside unbuildable project? it looks like bureaucracy - formally log4j is updated but actually those commits are useless
@danielbeaudreau maybe it make sense close repos with unused projects or put some kind of disclaimer into readme?

**Comment by msbukal** [comment]
We'll follow up with a fix for the dependency, but updating log4j is a separate issue - the repo fails to build regardless.

**Comment by danielbeaudreau** [comment]
Hey Egor, thanks for pointing out the build/dependency issue.
As Milena mentioned we will attempt to fix the build and create a new release as a follow up.

**Comment by msbukal** [comment]
Attempting to upgrade qupath version and fix presubmit here: https://github.com/GoogleCloudPlatform/qupath-chcapi-extension/pull/40

**Pull request merged**
